package a00878366.comp3717.bcit.ca.opendata.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import a00878366.comp3717.bcit.ca.opendata.database.schema.Category;
import a00878366.comp3717.bcit.ca.opendata.database.schema.DataSet;

import a00878366.comp3717.bcit.ca.opendata.database.schema.CategoryDao;
import a00878366.comp3717.bcit.ca.opendata.database.schema.DataSetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig dataSetDaoConfig;

    private final CategoryDao categoryDao;
    private final DataSetDao dataSetDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        dataSetDaoConfig = daoConfigMap.get(DataSetDao.class).clone();
        dataSetDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        dataSetDao = new DataSetDao(dataSetDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(DataSet.class, dataSetDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        dataSetDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public DataSetDao getDataSetDao() {
        return dataSetDao;
    }

}
